### ISSUE TITLE
在本地服务器连接不上，请大神指导

### ISSUE THREAD

**Issue by GGwujun** [beautifulBoys/vue-socket.io#1]
![image](https://cloud.githubusercontent.com/assets/17949342/24044236/751fd8a8-0b55-11e7-914f-9ac17c6b7e22.png)

![Uploading 1M5RMP7DS8TD03WH2%JHCGX.png…]()

**Comment by guntertien** [comment]
room 的324行，自己输入地址

**Comment by beautifulBoys** [comment]
楼上回复的对的，本地服务器需要换成自己的IP地址（room 的324行），自己的IP怎么看：win+R -> ipconfig -> 无线局域WiFi里的Ipv4为本地IP地址。
我加在readme.md里吧！
