### ISSUE TITLE
前端有問題開不起來

### ISSUE THREAD

**Issue by jeremysu0131** [beautifulBoys/vue-socket.io#2]
Hi:

前端啟動時會有問題無法運行
```bash
 WARNING  Compiled with 2 warnings                                                                                        13:11:08


  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  src/index.js:16:10
  } else {}
            ^


✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/eol-last

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  in ./src/lib/check.js

20:19-26 "export 'Browser' was not found in './browser.js'
```

**Comment by beautifulBoys** [comment]
你好！
谢谢来访。你遇到的报错信息为 eslint 代码格式的报错。

` WARNING  Compiled with 2 warnings                                                                                        13:11:08


  ✘  http://eslint.org/docs/rules/eol-last  Newline required at end of file but not found
  src/index.js:16:10
  } else {}
            ^


✘ 1 problem (1 error, 0 warnings)


Errors:
  1  http://eslint.org/docs/rules/eol-last

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 warning  in ./src/lib/check.js`
这个是文件最后需要留一个空行（Newline required at end of file but not found）。
可以通过该链接来查看原因：http://eslint.org/docs/rules/eol-last
----------------------------------------------------------------------------
這個是文件最後需要留壹個空行（Newline required at end of file but not found）。
可以通過該鏈接來查看原因：http://eslint.org/docs/rules/eol-last
----------------------------------------------------------------------------
`20:19-26 "export 'Browser' was not found in './browser.js'`
下方这个警告是找不到 Browser 导致的。检测浏览器版本的功能是由开源的第三方库（https://github.com/mumuy/browser）提供，而它没有提供相对应的npm包，所以在不修改源代码的基础上，采用了这种兼容的方式。在我找到更好的方法前，这个警告暂时先忽略，它不会影响项目运行。
----------------------------------------------------------------------------
`20:19-26 "export 'Browser' was not found in './browser.js'`
下方這個警告是找不到 Browser 導致的。檢測瀏覽器版本的功能是由開源的第三方庫（https://github.com/mumuy/browser）提供，而它沒有提供相對應的npm包，所以在不修改源代碼的基礎上，采用了這種兼容的方式。在我找到更好的方法前，這個警告暫時先忽略，它不會影響項目運行。
----------------------------------------------------------------------------


以上，谢谢！
欢迎来信讨论技术相关问题，共同进步。
李鑫 - 2018.04.28 18:07

**Comment by 2oops** [comment]
Obviously，like the first issue, maybe you can consider removing **browser.js**. I know, you wanna make your project better, but, currently the detection of browser version may be unnecessary.
